FROM node:20-alpine

WORKDIR /app
RUN mkdir -p /opt/node_modules
COPY ./package.json /app
COPY ./package-lock.json /app

RUN npm cache clean --force

RUN npm install --force

COPY ./ /app

RUN npm run build

COPY . .

ARG CLIENT_PORT

ENV PORT=$CLIENT_PORT

EXPOSE $PORT

CMD ["npm", "run", "preview"]