# Sử dụng image Nginx chính thức từ Docker Hub
FROM nginx:1.18.0

# Copy file cấu hình nginx tùy chỉnh vào trong container
# COPY ./nginx.conf /etc/nginx/nginx.conf
# COPY ./ssl /etc/ssl/  # Thư mục chứa chứng chỉ SSL (client-cert.pem và client-key.pem)
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./ssl /etc/nginx/ssl 

# Lệnh mặc định để chạy Nginx trong container
CMD ["nginx", "-g", "daemon off;"]