FROM nginx:1.18.0
# Copy template cấu hình và thư mục SSL vào container
COPY ./ssl /etc/nginx/ssl
COPY ./nginx.conf /etc/nginx/nginx.conf
# Tạo thư mục ssl nếu chưa có (tùy trường hợp)
RUN mkdir -p /etc/nginx/ssl

# COPY docker-entrypoint.sh /docker-entrypoint.sh
# RUN chmod +x /docker-entrypoint.sh

# ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]

# ENTRYPOINT ["/bin/sh", "-c", "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"]
